skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
  
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]  
  
  root to: redirect('/cats')
end

skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div>
      <a href="<%=cats_url %>">Home</a>
      <% if logged_in? %>
        <p>Welcome, <%= current_user.user_name %></p>
        <form class="" action="<%= session_url(@current_user) %>" method="post">
          <input type="hidden" name="authenticity_token" value="form_authenticity_token">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" name="" value="Logout">
        </form>
      <% else %>
        <a href="<%=new_user_url %>">Sign Up</a>
        <a href="<%=new_session_url %>">Log In</a>
      <% end %>
    </div>
    <div>
      <% if flash[:errors] %>
        <ul>
          <% flash[:errors].each do |error| %>
          <li class="errors"><%=error %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div>
      <% current_user.cats.each do |cat| %>
        <%= "#{cat.id} #{cat.name}" %> 
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>