skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
  
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]  
  
  root to: redirect('/cats')
end

skeleton/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  
  validates :user_name, presence: true, uniqueness: true 
  validates :session_token, presence: true, uniqueness: true 
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  attr_reader :password
  
  after_initialize :ensure_session_token
  
  has_many :cats,
    foreign_key: :user_id,
    class_name: :Cat
    
  has_many :rental_requests,
    foreign_key: :user_id,
    class_name: :CatRentalRequest    
  
  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return user if user && user.is_password?(password)
  end
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def password=(pw)
    @password = pw 
    self.password_digest = BCrypt::Password.create(pw)
  end
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
  
end

skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def index
  #   @users = User.all
  #   render :index
  # end
  # before_action :require_login, only:[:destroy]
  before_action :require_logout, only:[:new, :create]
  
  def show
    @user = User.find(params[:id])
    render :show
  end
 
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to cats_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  # def edit
  #   @user = User.find(params[:id])
  #   render :edit
  # end
  # 
  # def update
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(user_params)
  #     redirect_to user_url(@user)
  #   else
  #     flash.now[:errors] = @user.errors.full_messages
  #     render :edit
  #   end
  # end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
  
  
end 

skeleton/app/views/users/_form.html.erb
<%# action = (type  ? cat_url(cat) : cats_url) %>
<%# method = (cat.persisted? ? :post : :post) %>

<% if type == 'login' %>
  <% action = session_url %> 
  <% method = :post %> 
  <% submit_text = 'Login' %> 
<% elsif type == 'signup' %>
  <% action = users_url %>
  <% method = :post  %> 
  <% submit_text = 'Sign up' %>
<% end %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token"> 
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="user_name">Username</label>
  <input
    type="text"
    name="user[user_name]"
    id="user_name"
    value="">

  <label for="password">Password</label>
  <input
    type="password"
    name="user[password]"
    id="password"
    value="">
  <br>
  <input type="submit" value="<%= submit_text %>">
</form>

skeleton/app/views/users/new.html.erb
<h1>This is the Sign Up Page</h1>

<%= render 'form', user: @user, type: 'signup' %>